"""
Synthetic Vignan University (VFSTR - Vadlamudi, Guntur) Institutional Evidence Dataset.
Contains rich pre-loaded institutional records covering academic, research, governance,
facilities, placements, and quality audit data across 2020-2025.
"""

from typing import List, Dict, Any

VIGNAN_DEPARTMENTS = [
    "Computer Science & Engineering (CSE)",
    "Electronics & Communication Engineering (ECE)",
    "Biotechnology (BT)",
    "Mechanical Engineering (ME)",
    "Management Studies (MBA)",
    "Internal Quality Assurance Cell (IQAC)",
    "Office of Dean R&D",
    "Office of Dean Academics",
    "Controller of Examinations (CoE)",
    "Training & Placement Cell (T&P)",
    "Estate & Green Campus Office",
    "Student Affairs & NSS Cell"
]

VIGNAN_ACADEMIC_YEARS = [
    "2024-25",
    "2023-24",
    "2022-23",
    "2021-22",
    "2020-21"
]

VIGNAN_EVIDENCE_STORE: List[Dict[str, Any]] = [
    # --- Criterion 1 / Curricular Aspects / NBA C1, C2 ---
    {
        "id": "EVD-VIG-101",
        "title": "Board of Studies (BoS) Minutes - R22 Curriculum Revision for B.Tech CSE",
        "department": "Computer Science & Engineering (CSE)",
        "academic_year": "2023-24",
        "document_type": "BoS Minutes & Resolutions",
        "issuing_authority": "Chairman BoS & Dean Academics, VFSTR",
        "content_summary": "Minutes of 14th BoS meeting resolving implementation of R22 Outcome-Based Education (OBE) curriculum with 32% new elective courses in AI, ML, Cloud Computing, Cyber Security, and IoT. Fully mapped with POs and PSOs with Bloom's Taxonomy indicators.",
        "raw_text": "VFSTR Department of Computer Science & Engineering 14th Board of Studies BoS meeting minutes. Outcome-Based Education OBE curriculum design R22 structure. Revision of syllabus carried out across all semesters. Introduction of new elective courses in Artificial Intelligence, Machine Learning, Cloud Computing, Cyber Security, Full Stack Development, and Internet of Things IoT. Mapping of Course Outcomes CO with Program Outcomes PO and Program Specific Outcomes PSO. Academic Council approval dated July 12, 2023.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C1", "1.1.1", "1.1.2", "1.2.1", "NBA-C1", "NBA-1.1", "NBA-C2", "NBA-2.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-02-10",
        "file_format": "PDF",
        "file_size": "4.2 MB"
    },
    {
        "id": "EVD-VIG-102",
        "title": "Annual Stakeholder Curriculum Feedback & Action Taken Report (ATR) 2023-24",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Action Taken Report (ATR)",
        "issuing_authority": "IQAC & Academic Council, VFSTR",
        "content_summary": "Comprehensive 5-stakeholder feedback analysis (Students N=4210, Alumni N=980, Employers N=85, Faculty N=340, Parents N=1120). Includes departmental ATRs approved by Academic Council introducing experiential industry internships and coding bootcamps.",
        "raw_text": "Internal Quality Assurance Cell IQAC VFSTR Structured Stakeholder Feedback Analysis on Curriculum and Action Taken Report ATR. Feedback collected from students, faculty, employers, alumni, and parents. Percentage of satisfaction 91.4%. Identified gap in hands-on industry tools addressed by introducing 12 new value-added skill courses and mandatory 6-month industrial internship for final year engineering students.",
        "status": "Verified",
        "completeness_score": 92,
        "missing_elements": ["Employer feedback sample from European hiring partners pending formal stamp"],
        "applicable_criteria": ["C1", "1.4.1", "NBA-C1", "NBA-1.2", "NBA-C7", "NBA-7.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-05-18",
        "file_format": "PDF",
        "file_size": "8.1 MB"
    },
    {
        "id": "EVD-VIG-103",
        "title": "Value-Added & Skill Certification Course Compendium (48 Courses)",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "Course Compendium & Attendance Register",
        "issuing_authority": "Dean Academics & Skill Development Cell",
        "content_summary": "Consolidated catalog and execution report of 48 value-added courses (Python for Data Science, Industrial Automation, Bio-informatics Tools, EV Powertrain Design, Six Sigma) with student enrollment (N=3,840) and completion certificates.",
        "raw_text": "VFSTR Skill Development Cell and Dean Academics Value-added courses imparting transferable life skills and technical proficiencies. 48 certified value added courses conducted across CSE, ECE, Mechanical, Biotechnology and MBA. 3840 students enrolled with 3610 awarded certificates of completion. Minimum 30 contact hours with assessment rubrics and practical labs.",
        "status": "Verified",
        "completeness_score": 88,
        "missing_elements": ["BioTech EV course attendance sheets for batch 2 need HoD counter-signature"],
        "applicable_criteria": ["C1", "1.3.2", "NBA-C2", "NBA-2.2"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-06-04",
        "file_format": "PDF",
        "file_size": "14.5 MB"
    },
    {
        "id": "EVD-VIG-104",
        "title": "Program Educational Objectives (PEOs) & PSO Formulation with DAB Minutes",
        "department": "Electronics & Communication Engineering (ECE)",
        "academic_year": "2022-23",
        "document_type": "DAB Minutes & Matrix",
        "issuing_authority": "HoD ECE & Department Advisory Board (DAB)",
        "content_summary": "Formal formulation and review of PEOs and PSOs for B.Tech ECE program with Department Advisory Board (DAB) and Program Assessment Committee (PAC) meeting records. Contains correlation matrices with institutional vision and mission.",
        "raw_text": "Department of Electronics and Communication Engineering ECE VFSTR. Formulation of Program Educational Objectives PEO, Program Outcomes PO, and Program Specific Outcomes PSO. Department Advisory Board DAB minutes with industry experts from Qualcomm, ISRO, and Texas Instruments. Mapping of PEOs with Department Mission and Institute Vision with detailed correlation justification matrix.",
        "status": "Verified",
        "completeness_score": 94,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C1", "NBA-1.1", "NBA-1.2", "NBA-1.3", "C1", "1.1.1"],
        "verified_by": "Dr. T. Pitchaiah (HoD ECE)",
        "verification_date": "2023-09-12",
        "file_format": "PDF",
        "file_size": "3.8 MB"
    },

    # --- Criterion 2 / Teaching-Learning / NBA C3, C4, C5, C8 ---
    {
        "id": "EVD-VIG-201",
        "title": "Admission Registers & Sanctioned Intake Verification Gazette (2020-2024)",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "Statutory Admission Gazette",
        "issuing_authority": "Director Admissions & Registrar, VFSTR",
        "content_summary": "AICTE / UGC approved sanctioned intake and verified admissions through V-SAT (Vignan Scholastic Aptitude Test), AP EAPCET, JEE Main, and ICET. Demand ratio averaged 1:4.8 with 92.4% overall seat occupancy.",
        "raw_text": "Vignan's Foundation for Science, Technology and Research VFSTR Admissions Gazette. Sanctioned intake approved by UGC and AICTE vs admitted students across B.Tech, M.Tech, MBA, MCA and Ph.D. programs. V-SAT national entrance test allotments, state counseling quota, category-wise reservation roster compliance (SC, ST, OBC, EWS, General). Average student intake enrollment percentage 92.4%.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C2", "2.1.1", "NBA-C4", "NBA-4.1"],
        "verified_by": "Dr. P. M. V. Rao (Registrar)",
        "verification_date": "2024-01-20",
        "file_format": "PDF",
        "file_size": "5.6 MB"
    },
    {
        "id": "EVD-VIG-202",
        "title": "Diagnostic Assessment & Special Schemes for Advanced & Slow Learners",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Institutional Policy & Execution Report",
        "issuing_authority": "Dean Academics & IQAC Coordinator",
        "content_summary": "First-year entry level diagnostic assessment identifying slow learners (<45% diagnostic score) and advanced learners (>75%). Policy report includes remedial coaching logs (N=420 students) and Undergrad Research Fellowship grants for advanced learners (N=85 projects).",
        "raw_text": "VFSTR Institutional Mechanism for Assessment of Student Learning Levels. Diagnostic baseline assessment test conducted post-induction. Special initiatives: Remedial tutoring classes, bilingual study material for slow learners, and Undergraduate Research Fellowship (UGRF) seed funding, hackathon bootcamps, and honors degree options for advanced learners. Pass percentage improvement from 58% to 84% in remedial cohorts.",
        "status": "Verified",
        "completeness_score": 90,
        "missing_elements": ["Biotechnology department remedial test attendance sheet for Sem II missing instructor signature"],
        "applicable_criteria": ["C2", "2.2.1", "NBA-C2", "NBA-2.2", "NBA-C8", "NBA-8.2"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-04-12",
        "file_format": "PDF",
        "file_size": "6.3 MB"
    },
    {
        "id": "EVD-VIG-203",
        "title": "Experiential & Project-Based Learning Implementation Dossier",
        "department": "Mechanical Engineering (ME)",
        "academic_year": "2023-24",
        "document_type": "Pedagogy Execution Dossier",
        "issuing_authority": "HoD Mechanical & Center for Excellence in Robotics",
        "content_summary": "Comprehensive documentation of student-centric pedagogy: 100% course integration with Project-Based Learning (PBL), SAE BAJA / Formula Student prototype fabrication, virtual labs (IIT Bombay collaboration), and industrial visits to ISRO Sriharikota and Amaravati Smart City.",
        "raw_text": "Department of Mechanical Engineering VFSTR Experiential Learning and Problem-Solving Methodologies. Student centric learning practices: Project-based learning PBL in Design of Machine Elements, Heat Transfer, and CAD/CAM. Formula Student racing car and electric all-terrain vehicle (e-ATV) fabrication in Centre of Excellence. LMS video lectures, virtual labs integration, and industrial internship reports.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["C2", "2.3.1", "NBA-C2", "NBA-2.2"],
        "verified_by": "Dr. L. Suvarna Raju (HoD Mechanical)",
        "verification_date": "2024-03-22",
        "file_format": "PDF",
        "file_size": "11.2 MB"
    },
    {
        "id": "EVD-VIG-204",
        "title": "Full-Time Faculty Master List with Doctoral Degree (Ph.D.) Records",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "HR Master Register & Degree Certificates",
        "issuing_authority": "Dean Academics & HR Directorate",
        "content_summary": "Verified roster of 420 full-time faculty across engineering, management, and basic sciences. 318 faculty possess Ph.D. degrees (75.7%), with verified doctoral certificates from premier institutions (IITs, NITs, Central Universities, VFSTR).",
        "raw_text": "VFSTR Full-Time Faculty Master Register 2023-24. Total full-time faculty strength: 420. Faculty with Ph.D. doctorate qualification: 318 (75.71%). Cadre ratio: 48 Professors, 86 Associate Professors, 286 Assistant Professors. Student to Faculty Ratio SFR: 1:14.8. Contains scanned doctoral degree certificates, appointment orders, and UGC-mandated qualification compliance.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C2", "2.4.2", "NBA-C5", "NBA-5.1", "NBA-5.2", "NBA-5.3"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-01-15",
        "file_format": "PDF",
        "file_size": "22.4 MB"
    },
    {
        "id": "EVD-VIG-205",
        "title": "Continuous Internal Evaluation (CIE) Automation & Examination SOP",
        "department": "Controller of Examinations (CoE)",
        "academic_year": "2023-24",
        "document_type": "Examination Manual & Logs",
        "issuing_authority": "Controller of Examinations, VFSTR",
        "content_summary": "Standard Operating Procedure (SOP) for transparent CIE and Semester End Examinations. Complete ERP integration for automated marks upload, barcode evaluation, grievance redressal turnaround within 3 days, and result declaration in average 11.2 days from final exam.",
        "raw_text": "Office of Controller of Examinations CoE VFSTR. Continuous Internal Evaluation CIE automation via Vignan ERP portal. Standard Operating Procedure for question paper setting with Bloom's Taxonomy taxonomy mapping, double valuation with barcoding, and automated moderation. Average result declaration time: 11.2 days. Transparent student grievance redressal mechanism with digitized answer scripts re-verification.",
        "status": "Verified",
        "completeness_score": 93,
        "missing_elements": ["Sample answer sheet digital re-evaluation audit logs for MBA Sem III pending export"],
        "applicable_criteria": ["C2", "2.5.1", "NBA-C2", "NBA-2.3"],
        "verified_by": "Dr. P. Subba Rao (CoE)",
        "verification_date": "2024-04-28",
        "file_format": "PDF",
        "file_size": "7.8 MB"
    },
    {
        "id": "EVD-VIG-206",
        "title": "Consolidated Course Outcomes (CO) and PO/PSO Attainment Reports",
        "department": "Computer Science & Engineering (CSE)",
        "academic_year": "2023-24",
        "document_type": "Attainment Calculation Dossier",
        "issuing_authority": "HoD CSE & OBE Coordinator",
        "content_summary": "Comprehensive direct (80% weight from Mid-term exams, assignments, semester-end results) and indirect (20% weight from course exit surveys) attainment reports for all 68 courses in B.Tech CSE. Overall program PO attainment achieved 82.6% of target threshold.",
        "raw_text": "VFSTR Department of Computer Science & Engineering OBE Direct and Indirect Attainment Calculation Dossier. Direct assessment using CIE and Semester End Exams SEE mapped with COs (80% weightage). Indirect assessment using Course End Surveys and Program Exit Surveys (20% weightage). Attainment threshold set at 60% marks. Batch 2020-2024 PO attainment summary: PO1 (88%), PO2 (84%), PO3 (81%), PO4 (78%), PO5 (89%), PO12 (83%). Action plan formulated for PO4 (Investigating complex problems).",
        "status": "Verified",
        "completeness_score": 94,
        "missing_elements": [],
        "applicable_criteria": ["C2", "2.6.2", "NBA-C3", "NBA-3.1", "NBA-3.2", "NBA-3.3", "NBA-C7", "NBA-7.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-06-15",
        "file_format": "PDF",
        "file_size": "16.8 MB"
    },

    # --- Criterion 3 / Research, Innovations and Extension / NBA C5 ---
    {
        "id": "EVD-VIG-301",
        "title": "Institutional Research Promotion Policy & Seed Grant Sanction Letters (2020-2024)",
        "department": "Office of Dean R&D",
        "academic_year": "2023-24",
        "document_type": "Policy & Sanction Orders",
        "issuing_authority": "Dean R&D & Finance Committee",
        "content_summary": "VFSTR Research Policy providing INR 145.5 Lakhs cumulative seed grants to 64 faculty members for preliminary experimental setups, patent filings, and prototype generation. Complete with audited utilization certificates.",
        "raw_text": "Vignan's Foundation for Science, Technology and Research Research Promotion Policy. Financial seed money grants allocated for newly joined faculty and interdisciplinary research teams. Total seed funding disbursed during assessment period: INR 145.50 Lakhs across 64 research projects. Audited financial statements, sanction orders, purchase receipts for specialized lab equipment and consumables, and outcome summary (18 Scopus papers generated from seed grants).",
        "status": "Verified",
        "completeness_score": 92,
        "missing_elements": ["3 seed grant utilization certificates for Biotechnology lack external auditor stamp"],
        "applicable_criteria": ["C3", "3.1.1", "NBA-C5", "NBA-5.5"],
        "verified_by": "Dr. G. Srinivasa Rao (Dean R&D)",
        "verification_date": "2024-03-10",
        "file_format": "PDF",
        "file_size": "9.4 MB"
    },
    {
        "id": "EVD-VIG-302",
        "title": "Extramural Sponsored R&D Projects Sanction Orders (DST-SERB, AICTE, DRDO, DBT)",
        "department": "Office of Dean R&D",
        "academic_year": "2023-24",
        "document_type": "Govt Grant Sanction Orders",
        "issuing_authority": "DST-SERB, DBT, AICTE, ISRO",
        "content_summary": "Extramural research project sanction orders worth INR 682.4 Lakhs received over the last 5 years from DST-SERB (CRG, TARE), DBT, AICTE (RPS), and DRDO. Verified with bank credit statements and UC submissions.",
        "raw_text": "VFSTR Sponsored Research and Consultancy Cell. Government and non-government funded research projects sanction letters. Total funding mobilized: INR 682.45 Lakhs across 24 funded research projects. Major grants: DST-SERB Core Research Grant in Nanomaterials (INR 48.5L), DBT grant in Bio-fuel production (INR 62.0L), AICTE RPS grant in Edge AI (INR 24.8L), DRDO naval research grant (INR 38.2L). Audited fund release certificates and project completion dossiers.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.2.1", "NBA-C5", "NBA-5.5"],
        "verified_by": "Dr. G. Srinivasa Rao (Dean R&D)",
        "verification_date": "2024-05-02",
        "file_format": "PDF",
        "file_size": "12.7 MB"
    },
    {
        "id": "EVD-VIG-303",
        "title": "Vignan Technology Business Incubator (TBI) & Startup Ecosystem Dossier",
        "department": "Office of Dean R&D",
        "academic_year": "2023-24",
        "document_type": "Incubator Report & MoUs",
        "issuing_authority": "Director Vignan-TBI & IIC President",
        "content_summary": "Institutional Innovation Council (IIC - 4 Star Rated) and Vignan TBI (12,000 sq.ft facility). 28 student and faculty startups incubated, 6 technologies transferred to MSMEs, and INR 42 Lakhs external angel funding secured.",
        "raw_text": "Vignan Innovation and Incubation Centre (TBI) and Institution's Innovation Council (IIC). 4-star rating by Ministry of Education Innovation Cell (MIC). 12,000 sq. ft. dedicated incubation space with 3D printers, IoT testing kits, and fabrication lab. 28 incubated startups in Agritech, HealthTech, AI diagnostics, and Renewable Energy. 6 Technology Transfer agreements signed with regional industries. IPR policy with 100% financial reimbursement for patent filings.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.3.1", "NBA-C4", "NBA-4.3"],
        "verified_by": "Dr. B. Nageswara Rao (Director TBI)",
        "verification_date": "2024-02-18",
        "file_format": "PDF",
        "file_size": "15.1 MB"
    },
    {
        "id": "EVD-VIG-304",
        "title": "Intellectual Property Rights (IPR) Registry: 42 Patents Published & 14 Granted",
        "department": "Office of Dean R&D",
        "academic_year": "2023-24",
        "document_type": "Patent Gazette & Grant Certificates",
        "issuing_authority": "Indian Patent Office (IPO) & USPTO",
        "content_summary": "Complete list of 42 patents published and 14 patents granted to VFSTR faculty and students in IoT sensor networks, biomedical devices, agricultural harvesting mechanisms, and nano-composites.",
        "raw_text": "VFSTR IPR Cell Consolidated Patent Register. 42 patent applications published in the Indian Patent Journal, 14 patents officially granted by Indian Patent Office and International patent offices. Includes patent certificates: 'Solar powered smart agricultural monitoring drone' (Grant #412890), 'Bio-degradable polymer composite packaging' (Grant #398214), 'AI-assisted ECG arrhythmia classifier' (Grant #425112).",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.4.2", "NBA-C5", "NBA-5.5"],
        "verified_by": "Dr. G. Srinivasa Rao (Dean R&D)",
        "verification_date": "2024-04-14",
        "file_format": "PDF",
        "file_size": "8.9 MB"
    },
    {
        "id": "EVD-VIG-305",
        "title": "Scopus & Web of Science Indexed Publications Manifest (2020-2024)",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Scopus / WoS Institutional Extract",
        "issuing_authority": "Dean R&D & Central Library",
        "content_summary": "Official Scopus and Web of Science extract with 2,410 indexed research papers (average 3.2 papers per full-time teacher per year). Institutional h-index reached 52 with 18,400+ total citations. All articles verified with VFSTR affiliation.",
        "raw_text": "VFSTR Institutional Research Publications Archive 2020-2024. Scopus / Web of Science / UGC CARE indexed publications count: 2,410 journal articles and conference proceedings. Average publications per faculty per year: 3.2. Institutional h-index: 52. Total citations: 18,450. Top publishing areas: Artificial Intelligence, Computer Networks, Material Science, Biotechnology, Signal Processing, Renewable Energy. Includes master CSV database with DOI, author names, journal impact factor, and citation counts.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.4.5", "NBA-C5", "NBA-5.5"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-06-01",
        "file_format": "CSV/PDF",
        "file_size": "18.6 MB"
    },
    {
        "id": "EVD-VIG-306",
        "title": "NSS & Community Outreach Programs: 68 Village & Health Drives",
        "department": "Student Affairs & NSS Cell",
        "academic_year": "2023-24",
        "document_type": "Outreach Activity Reports & Letters",
        "issuing_authority": "NSS Program Coordinator & District Collectorate",
        "content_summary": "68 community outreach programs conducted under Unnat Bharat Abhiyan (UBA) and NSS in 10 adopted villages around Vadlamudi, Tenali, and Chebrolu. Included blood donation camps, digital literacy for rural schools, and soil health testing.",
        "raw_text": "VFSTR NSS Cell and Unnat Bharat Abhiyan Cell Community Extension Activities. 68 organized extension programs in 10 adopted villages of Guntur district. Over 4,500 student volunteer participation days. Major initiatives: Mega Blood Donation Camps (1,420 units donated to Red Cross), Free medical and dental health checkup camps, Digital literacy drives for rural Zilla Parishad high school children, Water conservation and farmer awareness camps. Appreciation letters from Village Sarpanches and District Collector.",
        "status": "Verified",
        "completeness_score": 94,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.6.2"],
        "verified_by": "Dr. V. Radhakrishna (NSS Coordinator)",
        "verification_date": "2024-03-30",
        "file_format": "PDF",
        "file_size": "24.2 MB"
    },

    # --- Criterion 4 / Infrastructure / NBA C6, C10 ---
    {
        "id": "EVD-VIG-401",
        "title": "Academic Infrastructure: Smart Classrooms, IoT & Supercomputing Labs",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "Infrastructure Master Plan & Stock Asset Log",
        "issuing_authority": "Estate Officer & Dean Infrastructure",
        "content_summary": "Detailed infrastructure audit of 124 ICT-enabled smart classrooms, 84 specialized engineering/biotech laboratories, High-Performance Computing (HPC) GPU Cluster with NVIDIA A100 nodes, and 4 seminar halls with geo-tagged photographs.",
        "raw_text": "VFSTR Campus Infrastructure Audit Report. 124 smart classrooms equipped with interactive flat panels, LCD projectors, and lecture capture systems. 84 advanced laboratories across disciplines including NVIDIA GPU Supercomputing Lab, Keysight RF & Microwave Lab, Dassault 3D Experience CAD Lab, and Pilot Scale Bioreactor Facility. Total built-up academic area: 1,85,000 sq. meters. Geo-tagged photographs and asset register with CPWD valuation certificates.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C4", "4.1.1", "NBA-C6", "NBA-6.1", "NBA-6.2"],
        "verified_by": "Er. K. Sambasiva Rao (Estate Officer)",
        "verification_date": "2024-02-25",
        "file_format": "PDF",
        "file_size": "32.0 MB"
    },
    {
        "id": "EVD-VIG-402",
        "title": "Central Library E-Resources, IEEE/ScienceDirect Subscriptions & Shodhganga",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Library Subscription Invoices & Usage Stats",
        "issuing_authority": "University Librarian & Finance Officer",
        "content_summary": "NTR Vignan Central Library with 1,20,000+ volumes, annual e-resource subscription budget of INR 94.5 Lakhs (IEEE Xplore, ScienceDirect, Springer, ASME, ASCE, Scopus), Turnitin plagiarism software, and MoU with INFLIBNET Shodhganga.",
        "raw_text": "VFSTR NTR Vignan Central Library Annual E-Resources Dossier. Annual expenditure on journal subscriptions and e-books: INR 94.50 Lakhs. Subscriptions: IEEE Xplore All-Society Periodicals, ScienceDirect Elsevier (275 journals), Springer Nature, ASME, ASCE, Emerald, Scopus database, Turnitin anti-plagiarism license. Shodhganga repository synchronization with 320 Ph.D. theses uploaded. Remote access enabled via INFED for all 8,500 students and faculty.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["C4", "4.2.2", "NBA-C10", "NBA-10.3"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-04-05",
        "file_format": "PDF",
        "file_size": "8.5 MB"
    },
    {
        "id": "EVD-VIG-403",
        "title": "Campus IT Backbone, 10 Gbps Leased Line & Wi-Fi 6 Coverage Report",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "IT Network Topology & ISP Invoices",
        "issuing_authority": "Head IT Infrastructure & Networks",
        "content_summary": "10 Gbps redundant internet leased line (BSNL & Tata Tele) with 100% Wi-Fi 6 coverage across academic blocks, laboratories, hostels, and sports grounds. Fortinet Enterprise Firewall with 24/7 intrusion prevention.",
        "raw_text": "VFSTR IT Infrastructure and Campus Network Audit. Internet bandwidth: 10 Gbps leased line with dual carrier redundancy (BSNL 6 Gbps + Tata Tele 4 Gbps). 380 Cisco and Aruba Wi-Fi 6 access points deployed across all campus buildings, residential quarters, and student hostels. 10G optical fiber backbone connecting 18 buildings. Fortinet 1500D enterprise firewall with centralized authentication and cybersecurity logs.",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C4", "4.3.1", "NBA-C6", "NBA-6.2", "NBA-C10", "NBA-10.3"],
        "verified_by": "Mr. Ch. Srinivas (Head IT)",
        "verification_date": "2024-01-18",
        "file_format": "PDF",
        "file_size": "6.7 MB"
    },
    {
        "id": "EVD-VIG-404",
        "title": "Annual Maintenance Contracts (AMC) & Physical Facility Budget Audit",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "AMC Contracts & Audited Financials",
        "issuing_authority": "Finance Officer & Registrar",
        "content_summary": "Audited expenditure of INR 1,420 Lakhs (38.2% of non-salary budget) spent on physical and academic support facility maintenance, laboratory equipment calibration, diesel generators (1500 kVA), and green landscaping.",
        "raw_text": "VFSTR Estate Maintenance and Physical Facilities Financial Audit. Annual expenditure on infrastructure maintenance and augmentation: INR 1,420 Lakhs representing 38.2% of total operational expenditure excluding salaries. Includes Annual Maintenance Contracts AMC for high-end instruments (SEM, HPLC, XRD), 1500 kVA captive power generator backup, RO water treatment plants, lift maintenance, and IT hardware upkeep.",
        "status": "Verified",
        "completeness_score": 93,
        "missing_elements": ["Calibration certificate for Biotechnology GC-MS instrument expired in March 2024, renewal order in progress"],
        "applicable_criteria": ["C4", "4.4.1", "NBA-C6", "NBA-6.1", "NBA-C10", "NBA-10.2"],
        "verified_by": "Er. K. Sambasiva Rao (Estate Officer)",
        "verification_date": "2024-05-20",
        "file_format": "PDF",
        "file_size": "10.4 MB"
    },

    # --- Criterion 5 / Student Support / NBA C4, C9 ---
    {
        "id": "EVD-VIG-501",
        "title": "Vignan Merit & Means Scholarships Disbursement Register (2020-2024)",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "Scholarship Disbursement Ledger",
        "issuing_authority": "Dean Student Affairs & Finance Officer",
        "content_summary": "Institutional scholarships and fee concessions worth INR 1,840 Lakhs disbursed to 68.5% of enrolled students based on V-SAT ranks, EAPCET ranks, Sports excellence, single-parent/orphan status, and rural economic hardship.",
        "raw_text": "VFSTR Institutional Merit and Means Scholarship Register. 68.5% of total enrolled students benefited from institutional fee waivers and government welfare schemes (Jagananna Vidya Deevena JVD, National Scholarship Portal NSP). Institutional freeships disbursed: INR 1,840 Lakhs in 2023-24. Categories: Top 100 V-SAT rankers (100% fee waiver), sports quota international/national medalists, rural poverty concessions.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C5", "5.1.1"],
        "verified_by": "Dr. M. S. S. Rukmini (Dean Student Affairs)",
        "verification_date": "2024-03-15",
        "file_format": "PDF",
        "file_size": "13.8 MB"
    },
    {
        "id": "EVD-VIG-502",
        "title": "Campus Placements & Higher Education Manifest: 86.4% Progression",
        "department": "Training & Placement Cell (T&P)",
        "academic_year": "2023-24",
        "document_type": "Placement Offer Register & Higher Studies Proofs",
        "issuing_authority": "Dean Training & Placements, VFSTR",
        "content_summary": "Placement statistics for 2023-24 graduating batch: 1,480 eligible students, 1,280 campus placement offers (86.4% combined placement and higher studies). Marquee recruiters: Amazon (44 LPA), TCS Digital (7.5 LPA), Cognizant, Accenture, L&T, Hyundai.",
        "raw_text": "VFSTR Training and Placement Cell Annual Report 2023-24. Total graduating batch eligible: 1,480. Students placed through campus recruitment: 1,180 (79.7%). Students progressed to higher education (GATE, GRE, CAT, MS abroad in USA/Germany): 100 (6.7%). Overall placement and progression index: 86.4%. Highest CTC: 44.0 LPA (Amazon). Average CTC: 6.2 LPA. Complete offer letters, company lists, and student salary slips verified by IQAC.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C5", "5.2.1", "NBA-C4", "NBA-4.3"],
        "verified_by": "Dr. D. Vijaya Ramu (Dean Placements)",
        "verification_date": "2024-06-20",
        "file_format": "PDF/XLSX",
        "file_size": "26.5 MB"
    },
    {
        "id": "EVD-VIG-503",
        "title": "National & Inter-University Sports / Cultural Medals Register (46 Awards)",
        "department": "Student Affairs & NSS Cell",
        "academic_year": "2023-24",
        "document_type": "Medal Register & AIU Certificates",
        "issuing_authority": "Director Physical Education & Cultural Cell",
        "content_summary": "Documentation of 46 medals and awards won by Vignan students at Association of Indian Universities (AIU) National Sports Meets (Volleyball, Athletics, Archery), South Zone Inter-Uni tournaments, and Vignan Mahotsav National Cultural Fest.",
        "raw_text": "VFSTR Directorate of Physical Education and Cultural Affairs. 46 awards and medals won in national and inter-university sports and cultural competitions. Gold medals in South Zone Inter-University Volleyball Championship, AIU All-India Athletics, National Archery Championship, and Classical Dance at National Youth Festival. Verified with official AIU certificates and participation rosters.",
        "status": "Verified",
        "completeness_score": 92,
        "missing_elements": ["3 medal certificates for All India Inter-University Taekwondo missing official AIU seal copy"],
        "applicable_criteria": ["C5", "5.3.1"],
        "verified_by": "Dr. M. S. S. Rukmini (Dean Student Affairs)",
        "verification_date": "2024-02-28",
        "file_format": "PDF",
        "file_size": "15.3 MB"
    },
    {
        "id": "EVD-VIG-504",
        "title": "Registered Alumni Association Activities & Financial Endowment Records",
        "department": "Student Affairs & NSS Cell",
        "academic_year": "2023-24",
        "document_type": "Alumni Association Audited Accounts & Minutes",
        "issuing_authority": "President Vignan Alumni Association & Registrar",
        "content_summary": "Vignan Alumni Association (Reg. No. 412/2011). Active chapters in Hyderabad, Bengaluru, Chennai, USA (Bay Area), and UAE. INR 68.2 Lakhs contributed toward student innovation endowments, scholarships, and campus tree plantations.",
        "raw_text": "Vignan Alumni Association VFSTR Registered Society Act compliance. Active alumni chapters in Silicon Valley USA, Dallas, London, Hyderabad, Bengaluru, and Chennai. Alumni financial contributions: INR 68.20 Lakhs toward student innovation awards, economically backward scholarships, and book endowments. 42 guest lectures and mentorship sessions conducted by prominent alumni in Fortune 500 companies.",
        "status": "Verified",
        "completeness_score": 91,
        "missing_elements": ["Bay Area USA Chapter 2023 annual meet minutes pending secretary signature"],
        "applicable_criteria": ["C5", "5.4.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-05-12",
        "file_format": "PDF",
        "file_size": "7.1 MB"
    },

    # --- Criterion 6 / Governance & Management / NBA C10 ---
    {
        "id": "EVD-VIG-601",
        "title": "VFSTR Strategic Plan 2020-2025, NEP 2020 Alignment & BoM Minutes",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Institutional Strategic Plan & Board Minutes",
        "issuing_authority": "Board of Management & Vice-Chancellor, VFSTR",
        "content_summary": "Strategic Plan 2020-2025 document with quantitative key performance indicators (KPIs) aligned with NEP 2020 (Multiple Entry/Exit, ABC credits, Interdisciplinary Majors/Minors, Indian Knowledge Systems). Organogram with decentralized financial powers to Deans and HoDs.",
        "raw_text": "Vignan's Foundation for Science, Technology and Research Strategic Development Plan 2020-2025. Aligned with National Education Policy NEP 2020: Academic Bank of Credits (ABC) integration for 100% students, multidisciplinary minors in AI and Management for engineering students, experiential internships. Board of Management BoM meeting minutes approving decentralized financial powers (HoD sanction limit INR 1 Lakh, Dean sanction limit INR 5 Lakhs).",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C6", "6.1.1", "NBA-C10", "NBA-10.1"],
        "verified_by": "Dr. P. M. V. Rao (Registrar)",
        "verification_date": "2024-01-10",
        "file_format": "PDF",
        "file_size": "11.8 MB"
    },
    {
        "id": "EVD-VIG-602",
        "title": "Comprehensive E-Governance Deployment & ERP System Audit",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "ERP Audit Report & Module Logs",
        "issuing_authority": "Head IT & Director IQAC",
        "content_summary": "100% implementation of integrated ERP across 5 core areas: Administration, Finance & Accounts (Tally Prime/ERP), Student Admission (V-SAT CRM), Teaching-Learning (Moodle LMS), and Examination/Results automation.",
        "raw_text": "VFSTR Institutional E-Governance Deployment Report. Automated ERP modules operational: 1. Student lifecycle and admission portal, 2. Fee collection and payroll accounting, 3. Biometric and RFID attendance for staff and students, 4. Moodle Learning Management System LMS for course materials and quizzes, 5. Examination automation system with automated hall tickets, gradesheet generation, and DigiLocker synchronization. ISO 27001 cybersecurity certified.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C6", "6.2.2", "NBA-C10", "NBA-10.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-03-05",
        "file_format": "PDF",
        "file_size": "8.3 MB"
    },
    {
        "id": "EVD-VIG-603",
        "title": "Faculty Professional Development Financial Support Ledger (62.4% Supported)",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "Financial Reimbursement Register",
        "issuing_authority": "Dean Academics & Finance Directorate",
        "content_summary": "Disbursement of INR 48.6 Lakhs financial assistance to 262 faculty members (62.4% of full-time teachers) for presenting papers at IEEE/Springer international conferences and attending specialized AICTE ATAL FDPs.",
        "raw_text": "VFSTR Faculty Empowerment and Financial Assistance Policy. 262 full time faculty teachers provided financial support for registration fees, travel allowance (TA/DA), and professional body memberships (IEEE, ACM, CSI, ISTE). Total financial outlay: INR 48.60 Lakhs in 2023-24. Scanned copies of conference presentation certificates, payment vouchers, and sanction orders verified.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["C6", "6.3.2"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-04-20",
        "file_format": "PDF",
        "file_size": "9.1 MB"
    },
    {
        "id": "EVD-VIG-604",
        "title": "Internal Quality Assurance Cell (IQAC) Quarterly Minutes & AQAR Submissions",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "IQAC Minutes & Action Taken Dossier",
        "issuing_authority": "Director IQAC & Vice-Chancellor",
        "content_summary": "Proceedings and Action Taken Reports for all 4 statutory quarterly IQAC meetings in 2023-24. Annual Quality Assurance Report (AQAR) timely submitted to NAAC, internal/external academic audits conducted across all 18 teaching departments.",
        "raw_text": "VFSTR Internal Quality Assurance Cell IQAC Annual Governance Dossier. Minutes of 4 regular quarterly IQAC meetings with external quality experts from IIT Madras and ISRO. Comprehensive Annual Quality Assurance Report AQAR uploaded to NAAC portal. Internal academic and administrative audits AAA conducted with external peer review team. NIRF rank band 75-100 maintained in University category.",
        "status": "Verified",
        "completeness_score": 99,
        "missing_elements": [],
        "applicable_criteria": ["C6", "6.5.1", "NBA-C7", "NBA-7.1", "NBA-7.2"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-06-25",
        "file_format": "PDF",
        "file_size": "14.2 MB"
    },

    # --- Criterion 7 / Institutional Values / Best Practices ---
    {
        "id": "EVD-VIG-701",
        "title": "Gender Sensitization, POSH Committee & Women Safety Audit Dossier",
        "department": "Student Affairs & NSS Cell",
        "academic_year": "2023-24",
        "document_type": "Committee Minutes & Safety Reports",
        "issuing_authority": "Internal Complaints Committee (ICC) & Dean Student Affairs",
        "content_summary": "Women Empowerment Cell and Internal Complaints Committee (ICC) annual reports. 6 gender sensitization workshops conducted. Campus security audit with 640 high-definition CCTV cameras, biometric women's hostel entry, and dedicated 24/7 counseling psychologist.",
        "raw_text": "VFSTR Gender Equity and Campus Safety Audit. Measures for promotion of gender equity: Annual gender sensitization action plan, 6 workshops on cyber safety and POSH compliance for female students and staff. Physical safety infrastructure: 640 CCTV cameras covering 100% common campus zones, biometric access control for girls hostels with female security guards, dedicated professional counseling center with female full-time psychologist.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.1.1", "NBA-C10", "NBA-10.1"],
        "verified_by": "Dr. M. S. S. Rukmini (Dean Student Affairs)",
        "verification_date": "2024-02-14",
        "file_format": "PDF",
        "file_size": "11.5 MB"
    },
    {
        "id": "EVD-VIG-702",
        "title": "Green, Energy & Environmental Audit: 1 MW Rooftop Solar & STP Water Recycling",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "Certified External Green Audit & Commissioning Docs",
        "issuing_authority": "BEE Certified Energy Auditor & Estate Directorate",
        "content_summary": "External Green & Energy Audit by Bureau of Energy Efficiency (BEE) certified agency. 1.0 MW rooftop solar PV plant meeting 42% of campus electricity, 500 KLD Sewage Treatment Plant (STP) with 100% treated water recycled for horticulture.",
        "raw_text": "VFSTR Environmental Consciousness and Sustainability Report. 1.0 MW grid-connected rooftop solar photovoltaic power plant generating 14.2 Lakh units annually (commissioning certs and APCPDCL solar net-metering bills). 500 KLD Sewage Treatment Plant STP recycling 100% greywater for campus lawns and botanical gardens. Rainwater harvesting pits (42 units with 2.8 Crore liters recharge capacity). Certified Energy, Green, and Environment Audit reports.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.1.2"],
        "verified_by": "Er. K. Sambasiva Rao (Estate Officer)",
        "verification_date": "2024-04-10",
        "file_format": "PDF",
        "file_size": "17.4 MB"
    },
    {
        "id": "EVD-VIG-703",
        "title": "Institutional Best Practice 1: Integrated Experiential Internship & Skill Passport",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Best Practice Case Study Dossier",
        "issuing_authority": "Director IQAC & Dean Academics",
        "content_summary": "Institutional Best Practice write-up in NAAC prescribed format: 'Integrated Experiential Internship & Skill Passport' ensuring 100% final-year students undertake 6-month industrial internship with corporate stipend and continuous industry mentoring.",
        "raw_text": "VFSTR Institutional Best Practice I in NAAC Format. Title: 'Integrated Experiential Internship and Digital Skill Passport'. Objectives: Bridging industry-academia skill gap and boosting employability. Context & Practice: Mandatory full semester (6 months) industrial internship in VIII semester with credit transfer. Digital Skill Passport tracking 24 industry competencies. Outcomes: 340% increase in pre-placement offers (PPOs), median salary increased by 28% to 6.2 LPA.",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.2.1", "NBA-C2", "NBA-2.2", "NBA-C7", "NBA-7.2"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-05-15",
        "file_format": "PDF",
        "file_size": "8.8 MB"
    },
    {
        "id": "EVD-VIG-704",
        "title": "Institutional Best Practice 2: Comprehensive Civil Services & GATE Coaching Cell",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Best Practice Case Study Dossier",
        "issuing_authority": "Director IQAC & Dean Student Affairs",
        "content_summary": "Institutional Best Practice II: 'Free Institutional In-House Civil Services & GATE Foundation Academy' providing structured evening coaching, test series, and guest lectures by serving IAS/IPS officers from 2nd year onwards.",
        "raw_text": "VFSTR Institutional Best Practice II in NAAC Format. Title: 'In-House Competitive Examination Academy for UPSC, GATE and State Services'. Context & Practice: Free specialized coaching embedded into daily timetable after regular academic hours. Outcome: 14 students cracked UPSC Civil Services / APPSC Group I in last 4 years; 142 students qualified GATE with top 500 AIR ranks securing admission in IITs and PSU jobs in ONGC, IOCL, and NTPC.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.2.1", "NBA-C4", "NBA-4.3"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-05-16",
        "file_format": "PDF",
        "file_size": "7.9 MB"
    },
    {
        "id": "EVD-VIG-705",
        "title": "Institutional Distinctiveness: Rural Skilling, AgriTech Innovation & Tribal Outreach",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Distinctiveness Narrative & Field Reports",
        "issuing_authority": "Vice-Chancellor & Director IQAC",
        "content_summary": "Comprehensive portrait of Vignan's distinctiveness: Empowering rural youth of Andhra Pradesh through cutting-edge technology skilling, low-cost AgriTech solutions for chilli/cotton farmers of Guntur region, and female education scholarships.",
        "raw_text": "VFSTR Institutional Distinctiveness Narrative. Thrust Area: 'Empowering Rural Andhra Pradesh through Technology Skilling and Affordable AgriTech Innovations'. Established Centre of Excellence in Agricultural Robotics and Soil Nanotechnology developing low-cost automated sprayers and moisture sensors for Guntur chilli farmers. 65% student intake drawn from rural agricultural backgrounds with subsidized education.",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.3.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-05-18",
        "file_format": "PDF",
        "file_size": "10.6 MB"
    },

    # --- NBA Specific Evidence (Criteria 5, 8, 9, 10) ---
    {
        "id": "EVD-VIG-801",
        "title": "First Year Basic Sciences Faculty Qualifications & Pass Percentage Analytics",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "First Year Academic Dossier",
        "issuing_authority": "Dean Basic Sciences & Dean Academics",
        "content_summary": "Roster of 58 first-year Mathematics, Physics, Chemistry, and Humanities faculty (84.5% Ph.D. holders). Student-faculty ratio maintained at 1:14.2. First-year pass percentage recorded at 81.6% with 3-week induction program.",
        "raw_text": "VFSTR Division of Basic Sciences and Humanities First Year Academics Report. 58 full-time faculty teaching Engineering Mathematics, Applied Physics, Engineering Chemistry, English for Engineers, and Python Programming. 49 faculty hold Ph.D. doctorates (84.48%). 3-week mandatory AICTE Student Induction Program SIP conducted. First year overall academic pass percentage: 81.6% with average GPA 7.82.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C8", "NBA-8.1", "NBA-8.2"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-02-12",
        "file_format": "PDF",
        "file_size": "6.8 MB"
    },
    {
        "id": "EVD-VIG-802",
        "title": "Proctorial Mentoring System Logbooks & Student Counseling Records",
        "department": "Student Affairs & NSS Cell",
        "academic_year": "2023-24",
        "document_type": "Mentoring Register & Sample Diaries",
        "issuing_authority": "Dean Student Affairs & Chief Proctor",
        "content_summary": "1:18 mentor-to-mentee ratio across all departments. Structured fortnightly mentoring meetings recording academic progress, psychological well-being, attendance monitoring, and parent communication logs.",
        "raw_text": "VFSTR Proctorial Mentoring System Institutional Dossier. Dedicated faculty proctor assigned for every batch of 18-20 students throughout their 4-year degree. Fortnightly one-on-one counseling sessions logged in ERP proctor diary. Academic performance tracking, remedial coaching recommendations, career counseling, and immediate parent communication on attendance shortage (<75%).",
        "status": "Verified",
        "completeness_score": 94,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C9", "NBA-9.1", "C2", "2.2.1"],
        "verified_by": "Dr. M. S. S. Rukmini (Dean Student Affairs)",
        "verification_date": "2024-03-08",
        "file_format": "PDF",
        "file_size": "8.7 MB"
    },
    {
        "id": "EVD-VIG-803",
        "title": "Professional Student Chapters (IEEE, ACM, CSI, ASME) Annual Activity Reports",
        "department": "Computer Science & Engineering (CSE)",
        "academic_year": "2023-24",
        "document_type": "Chapter Annual Reports & Event Logs",
        "issuing_authority": "IEEE VFSTR Student Branch Counselor",
        "content_summary": "Reports of 34 national hackathons, coding contests, and guest symposiums organized under IEEE VFSTR Student Branch, ACM Student Chapter, and CSI. Student membership exceeded 820 active members.",
        "raw_text": "VFSTR Technical Professional Societies Annual Dossier. Active student chapters: IEEE Student Branch (STB10021), ACM Chapter, CSI Student Chapter, ASME Chapter, and Indian Institute of Chemical Engineers (IIChE). 34 major technical events organized in 2023-24 including 'VignanHack 2023' (36-hour national hackathon with 600 participants), IEEE International Conference on Smart Systems, and Women in Engineering (WIE) summit.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C9", "NBA-9.2", "C5", "5.3.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-04-18",
        "file_format": "PDF",
        "file_size": "19.2 MB"
    },
    {
        "id": "EVD-VIG-804",
        "title": "Finance Committee Approvals & Audited Institutional Balance Sheets (3 Years)",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Statutory Audited Financial Statements",
        "issuing_authority": "Chartered Accountant & Finance Officer",
        "content_summary": "Statutory audited balance sheets and income/expenditure statements for FY 2021-22, 2022-23, and 2023-24 certified by independent Chartered Accountants. Budget allocation for academic and infrastructure augmentation utilized at 96.2%.",
        "raw_text": "Vignan's Foundation for Science, Technology and Research Statutory Financial Audit. Audited Balance Sheets, Income and Expenditure Statements, and Schedules of Fixed Assets for last 3 financial years audited by M/s Rao & Associates Chartered Accountants. Total institutional operating budget: INR 142.5 Crores. Budget allocation to academic infrastructure: INR 38.4 Crores with 96.2% utilization. No adverse audit remarks.",
        "status": "Verified",
        "completeness_score": 99,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C10", "NBA-10.2", "C4", "4.4.1", "C6", "6.2.2"],
        "verified_by": "Dr. P. M. V. Rao (Registrar)",
        "verification_date": "2024-06-30",
        "file_format": "PDF",
        "file_size": "15.7 MB"
    },
    {
        "id": "EVD-VIG-901",
        "title": "NIRF 2024 Institutional Data Submission Dossier (Overall & Engineering)",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Data Submission Dossier",
        "issuing_authority": "Director IQAC & Registrar, VFSTR",
        "content_summary": "Full NIRF parameters report for Teaching, Learning & Resources (TLR), Research & Professional Practice (RPC), Graduation Outcomes (GO), Outreach & Inclusivity (OI), and Perception (PR) with signed executive declaration.",
        "raw_text": "VFSTR Vadlamudi NIRF 2024 Institutional Data Submission. Approved student strength 8,420 across UG and PG. Faculty-to-student ratio 1:14.2. Over 81.2% regular faculty with Ph.D. qualifications. Annual capital expenditure on academic library and lab equipment: INR 18.2 Crores. Operational expenditure: INR 84.6 Crores. Publications indexed in Scopus/WoS: 1,842 in 3 years with 14,200 citations. Median placement salary: INR 6.2 LPA.",
        "status": "Verified",
        "completeness_score": 98,
        "missing_elements": [],
        "applicable_criteria": ["NIRF", "NIRF-TLR", "NIRF-RPC", "NIRF-GO", "NIRF-OI", "NIRF-PR", "C2", "2.1.1", "C3", "3.4.3", "NBA-C5"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-01-20",
        "file_format": "PDF",
        "file_size": "12.4 MB"
    },
    {
        "id": "EVD-VIG-902",
        "title": "Outcome Based Education (OBE) Program Outcomes (PO) Attainment Compendium",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "PO/PSO Attainment Matrix",
        "issuing_authority": "Dean Academics & Controller of Examinations",
        "content_summary": "Direct and indirect attainment calculations for PO1-PO12 and PSO1-PSO3 across 11 engineering disciplines using continuous internal evaluation (CIE) and semester-end exams (SEE).",
        "raw_text": "Outcome Based Education (OBE) Attainment Analysis VFSTR. Course outcome (CO) attainment computed for each course based on 70% threshold. PO direct attainment synthesized from CO-PO mapping weights. Indirect attainment evaluated from Graduate Exit Survey (N=1,420) and Alumni Survey (N=580). Average PO attainment achieved: 82.4% with specific action plans for PO5 (Modern Tool Usage) and PO7 (Environment and Sustainability).",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C3", "NBA-3.1", "NBA-3.2", "NBA-3.3", "C2", "2.6.1", "C1", "1.1.1"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-05-30",
        "file_format": "PDF",
        "file_size": "16.1 MB"
    },
    {
        "id": "EVD-VIG-903",
        "title": "Annual Green Campus, Energy and Environmental Audit Report (ISO 14001)",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "Environmental Audit Report",
        "issuing_authority": "Estate Officer & Certified Energy Auditor (BEE)",
        "content_summary": "Comprehensive third-party green audit, carbon footprint evaluation, 1.2 MW rooftop solar generation yield, sewage treatment plant (STP 500 KLD) recycled water utilization, and plastic-free campus compliance.",
        "raw_text": "VFSTR Vadlamudi Environmental and Green Audit Report. 1.2 MW grid-connected rooftop solar photovoltaic power plant generating 42% of campus electrical requirements. 500 KLD Sewage Treatment Plant STP with 100% wastewater recycled for horticulture and landscaping. Rainwater harvesting pits (N=24) replenishing local groundwater table. Green canopy coverage exceeds 44% of total 104-acre campus area.",
        "status": "Verified",
        "completeness_score": 97,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.1.1", "7.1.3", "7.1.8", "NBA-C10"],
        "verified_by": "Dr. P. M. V. Rao (Registrar)",
        "verification_date": "2024-04-22",
        "file_format": "PDF",
        "file_size": "9.5 MB"
    },
    {
        "id": "EVD-VIG-904",
        "title": "Barrier-Free Environment & Divyangjan Accessibility Facilities Audit",
        "department": "Estate & Green Campus Office",
        "academic_year": "2023-24",
        "document_type": "Accessibility Certification",
        "issuing_authority": "Equal Opportunity Cell & University Architect",
        "content_summary": "Institutional facilities for persons with disabilities: ramps with handrails in all academic blocks, braille tactile pathways, accessible passenger elevators, specialized restrooms, and screen-reading software in central library.",
        "raw_text": "VFSTR Institutional Audit of Facilities for Differently-Abled (Divyangjan) Students and Staff. All 8 academic blocks equipped with disabled-friendly ramps, tactile walking floor tiles, and dedicated braille-signage lifts. Specialized Divyangjan restrooms on all floors. Central Library equipped with JAWS screen-reading software and assistive motorized wheelchairs. Human assistance protocol in place for examination scribes.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C7", "7.1.8", "NIRF-OI", "NBA-C9", "NBA-9.1"],
        "verified_by": "Dr. M. S. S. Rukmini (Dean Student Affairs)",
        "verification_date": "2024-03-15",
        "file_format": "PDF",
        "file_size": "5.3 MB"
    },
    {
        "id": "EVD-VIG-905",
        "title": "Corporate Training & Industrial Consultancy Revenue Statement (AY 2023-24)",
        "department": "Office of Dean R&D",
        "academic_year": "2023-24",
        "document_type": "Consultancy Register & Invoices",
        "issuing_authority": "Dean R&D & Finance Officer",
        "content_summary": "Audited consultancy projects undertaken for Amaravati Smart City, AP Pollution Control Board, Tata Consultancy Services, and Hetero Drugs generating INR 2.42 Crores revenue.",
        "raw_text": "VFSTR Dean R&D Industrial Consultancy and Executive Corporate Training Register. Total consultancy revenue earned in AY 2023-24: INR 2,42,80,000 across 28 sanctioned industrial projects. Key clients include Andhra Pradesh Pollution Control Board APPCB, Amaravati Development Corporation, Hetero Drugs, and Schneider Electric. Institutional policy reserves 40% for faculty investigators and 60% for laboratory modernization fund.",
        "status": "Verified",
        "completeness_score": 94,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.5.1", "NIRF-RPC", "NBA-C5", "NBA-5.3"],
        "verified_by": "Dr. G. Srinivasa Rao (Dean R&D)",
        "verification_date": "2024-06-12",
        "file_format": "PDF",
        "file_size": "7.1 MB"
    },
    {
        "id": "EVD-VIG-906",
        "title": "Course File Quality Audit & Bloom's Taxonomy Question Paper Rubrics",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Academic Audit Report",
        "issuing_authority": "Academic Audit Committee & Director IQAC",
        "content_summary": "Comprehensive external peer audit of 420 semester course files, continuous internal evaluation rubrics, Bloom's Revised Taxonomy level distributions in question papers, and lab manual validations.",
        "raw_text": "VFSTR Internal Quality Assurance Cell IQAC Semester Course File Audit Report. All 420 courses verified for 12 mandatory course file components: Syllabus, CO-PO articulation matrix, course delivery plan, lecture notes, question paper Bloom's taxonomy distribution (minimum 30% higher order thinking L4-L6), continuous evaluation sample scripts, and CO attainment worksheets.",
        "status": "Verified",
        "completeness_score": 95,
        "missing_elements": [],
        "applicable_criteria": ["NBA-C2", "NBA-2.1", "NBA-2.2", "C1", "1.1.1", "C2", "2.5.1"],
        "verified_by": "Dr. K. Ramamohan (Director IQAC)",
        "verification_date": "2024-02-28",
        "file_format": "PDF",
        "file_size": "11.8 MB"
    },
    {
        "id": "EVD-VIG-907",
        "title": "International & National Academic Collaborative MoUs & Exchange Registry",
        "department": "Office of Dean Academics",
        "academic_year": "2023-24",
        "document_type": "MoU Register & Activity Dossier",
        "issuing_authority": "Director International Relations & Dean Academics",
        "content_summary": "Registry of 42 active academic MoUs (University of Massachusetts, Dongguk University Korea, ISRO, CSIR-IICT) with tangible evidence of student exchange (N=48), faculty fellowships, and joint symposiums.",
        "raw_text": "VFSTR Directorate of International Relations and Academic MoUs. 42 functional Memorandums of Understanding MoUs with leading foreign universities and national premier research centers. 48 undergraduate and postgraduate students completed semester-abroad study in USA, South Korea, and Taiwan with credit transfer. 14 visiting international professors delivered specialized courses in AI, Bio-Nanotechnology, and Robotics.",
        "status": "Verified",
        "completeness_score": 93,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.7.1", "NIRF-OI", "NBA-C1", "NBA-1.1"],
        "verified_by": "Dr. N. Veeranjaneyulu (Dean Academics)",
        "verification_date": "2024-05-14",
        "file_format": "PDF",
        "file_size": "8.4 MB"
    },
    {
        "id": "EVD-VIG-908",
        "title": "Vignan Innovation Center & Startup Incubation Gazette (CIIE)",
        "department": "Internal Quality Assurance Cell (IQAC)",
        "academic_year": "2023-24",
        "document_type": "Incubation Gazette & CIN Certificates",
        "issuing_authority": "Director CIIE & Registrar",
        "content_summary": "Annual report of Center for Innovation, Incubation and Entrepreneurship (CIIE): 18 student-led startups incubated, INR 65 Lakhs seed capital disbursed, 12 registered Private Limited entities with active CINs.",
        "raw_text": "VFSTR Center for Innovation, Incubation and Entrepreneurship CIIE Annual Gazette. 18 technology and agri-business startups actively incubated on campus with prototyping lab, patent filing support, and legal advisory. 12 startups registered under Ministry of Corporate Affairs with valid Corporate Identification Numbers CIN. Total institutional seed grant capital disbursed: INR 65 Lakhs. Generated 86 direct jobs.",
        "status": "Verified",
        "completeness_score": 96,
        "missing_elements": [],
        "applicable_criteria": ["C3", "3.2.1", "NBA-C4", "NBA-4.3", "NIRF-RPC"],
        "verified_by": "Dr. G. Srinivasa Rao (Dean R&D)",
        "verification_date": "2024-06-25",
        "file_format": "PDF",
        "file_size": "13.2 MB"
    }
]


def get_demo_evidence_list() -> List[Dict[str, Any]]:
    """Returns the pre-loaded synthetic evidence store."""
    return list(VIGNAN_EVIDENCE_STORE)
